### PR TITLE
Create a page for data logging methods in the software section

### PR DESCRIPTION
**Pull request by wolcottm**
Please let me know what you think. I'm no expert by any means, but I didn't see this info on the wiki.

I've never made a pull request before so let me know if I'm not doing it right.

### CODE REVIEW

**Comment by WillXuCodes** [comment]
Hello @wolcottm ,

This is a great idea for an article and an awesome start for an article. 

Just a few thoughts on this so far: 
1. Logging to a file in C++ could be streamlined a little better, using smart pointers or even a class with a destructor could allow the file to be closed automatically without a dedicated close function. 
2. Logging to the terminal via std::out/printf is something we could also probably add. This is the most popular way to do things at the moment. Feel free to include this library I made a while ago that has utilities: https://github.com/WillXuCodes/debugging-macros/blob/main/debug-macros.h
3. Logging to LLEMU would be nice as well, I think both this and logging via std::out/C++ would be similar in context (quick variable tracking) to controller logging. 
4. I think we should also mention that LVGL is a PROS specific feature at this point, yes I know VEXCode has it ported in certain flavors but while it was James who ported it I'm not sure if it's officially supported or worth the tech support headache (this is more minor of a thing). 

We appreciate the contribution!

**Comment by wolcottm** [comment]
Hi Will, do you plan to make those edits? I don't feel I'd know what I'm talking about on those topics you mentioned.

**Comment by WillXuCodes** [comment]
> Hi Will, do you plan to make those edits? I don't feel I'd know what I'm talking about on those topics you mentioned.

I sure can if needed, we can merge with your current changes and update if needed. I'm going to wait a bit for the student leadership to respond before doing so. 

Also, feel free to embed a link in the contributors section to your team's website if you have one!

**Comment by wolcottm** [comment]
Hi Will, I embedded a link to our team's website in data-logging.md and I also added a short section on custom path planners in path-planning.md. Do you know if I need to do anything to update the pull request? Thank you. I'm also not sure if I the image I added to path-planning works correctly. 

I also wanted to note that https://purduesigbots.com/ doesn't seem to work for me.

**Comment by WillXuCodes** [comment]
> Hi Will, I embedded a link to our team's website in data-logging.md and I also added a short section on custom path planners in path-planning.md. Do you know if I need to do anything to update the pull request? Thank you. I'm also not sure if I the image I added to path-planning works correctly.
> 
> I also wanted to note that https://purduesigbots.com/ doesn't seem to work for me.

Looking into the main website being down but somebody did mention that, it seems like we're having some technical issues on the CS server end. I'll get back to you on the review when I can. I think the student leadership/team is bogged down with finals and worlds at the moment.

**Comment by WillXuCodes** [comment]
Looks good to me, I'm going to merge this for the new season (Thank you so much for the contribution!)

**Comment by matthewjd24** [comment]
Thank you! (Sorry same person, different account). Also, I'm not an expert on Github, should the Data Logging page be showing up on the wiki?

**Comment by WillXuCodes** [comment]
The github sync is a little finnicky, worst case scenario I will manually port your article if it doesn't show up tommorow night.

**Comment by matthewjd24** [comment]
Thanks!

**Comment by matthewjd24** [comment]
I just wanted to follow up about that page not showing up. It might be because I did something wrong too :)

**Comment by WillXuCodes** [comment]
No it's my bad, I forgot to port it properly as I've been in multiple job interviews and am about to make a cross country move. I've been meaning to reach out on discord soon as well.

**Comment by noam987** [comment]
I'm porting it over now. Should be on the site later tonight

**Comment by matthewjd24** [comment]
Thank you, hope your interviews went well.

**Comment by noam987** [comment]
Should be merged in. might take a few minutes for the changes to propagate. Thanks again for your contribution to the wiki.

**Pull request merged**
