### PR TITLE
Create Vex Joints

### PR DESCRIPTION
**Pull request by 2775Josh**
First hardware file, explanation of four Vex joints and their uses.

### CODE REVIEW

**Comment by WillXuCodes** [comment]
Liking the article so far! I think adding some actual examples of how these joints can be applied mechanically would help to enhance the article as well.

**Comment by 2775Josh** [comment]
Absolutely, I'll find one or two examples for each and update the article :)

**Comment by 2775Josh** [comment]
I've added real-robot examples for the Vex Joints, as well as created a new article "Vex Drivetrains".

**Comment by kunwarsahni01** [comment]
This LGTM

**Pull request merged**
